// Initial Mock Data for TrocaJá Marketplace — UniBarretos Consultancy Release

export const INITIAL_PERSONAS = [
  // LOCADORES & LOCATÁRIOS (CLIENTES P2P / PRO)
  {
    id: 'carlos',
    name: 'Carlos Menezes',
    role: 'Locador Amador (P2P)',
    badge: 'Locador P2P',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    details: 'Marceneiro, 34 anos • Anuncia ferramentas para complementar renda',
    quote: 'Tenho medo de emprestar minha serra de R$ 2.500 e voltar quebrada sem ressarcimento.',
    metrics: { itemsListed: 4, monthlyRevenue: 1250, activeRentals: 2 },
    isPro: false,
    userRole: 'locador',
    password: '1a2b3c'
  },
  {
    id: 'bianca',
    name: 'Bianca Ferreira',
    role: 'Locatária Eventual (P2P)',
    badge: 'Locatário',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    details: 'Organizadora de festas, 27 anos • Aluga itens pontuais',
    quote: 'Não entendo bem a caução retida e fico desprotegida se houver cobrança sem explicação.',
    metrics: { itemsRented: 8, totalSpent: 2100, activeBooking: 1 },
    isPro: false,
    userRole: 'locatario',
    password: '1a2b3c'
  },
  {
    id: 'antenor',
    name: 'Antenor Silva (Ferragens Silva)',
    role: 'Parceiro Comercial PRO',
    badge: 'Lojista PRO (9%)',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    details: 'Dono de loja de ferragens, 58 anos • Ribeirão Preto/SP',
    quote: 'Preciso de relatório financeiro simples para o meu contador e Nota Fiscal automática de cada aluguel.',
    metrics: { storeItems: 42, monthlyRevenue: 14800, activeRentals: 15 },
    isPro: true,
    proSubscriptionStatus: 'ATIVA',
    userRole: 'lojista',
    password: '1a2b3c'
  },
  {
    id: 'diego',
    name: 'Diego Farias',
    role: 'Locatário Frequente',
    badge: 'Locatário VIP',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    details: 'Motorista de app, 30 anos • Aluga equipamentos de som/luz para eventos',
    quote: 'Não posso ter reservas duplicadas nem cancelamentos de última hora sem aviso.',
    metrics: { itemsRented: 24, totalSpent: 9400, activeBooking: 2 },
    isPro: false,
    userRole: 'locatario',
    password: '1a2b3c'
  },

  // EQUIPE OPERACIONAL & ATENDIMENTO
  {
    id: 'camila',
    name: 'Camila Torres',
    role: 'Atendente de Suporte (22 anos)',
    badge: 'Suporte L1',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    details: 'Atendente temporária • Atendimento direto via sistema com SLA',
    quote: 'Com o chat do sistema e motor de regras, resolvo os chamados sem divergência do time fixo.',
    metrics: { openTickets: 5, resolvedToday: 18, avgSlaMin: 12 },
    isPro: false,
    userRole: 'suporte',
    password: '1a2b3c'
  },
  {
    id: 'lucas',
    name: 'Lucas Andrade',
    role: 'Coord. Confiança & Segurança',
    badge: 'Analista T&S',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    details: 'Coordenador de T&S • Modera KYC, itens sensíveis e disputas de caução',
    quote: 'O motor de regras sugere a retenção justa de caução e eu mantenho a decisão humana auditável.',
    metrics: { pendingKYC: 3, pendingSensitive: 2, openDisputes: 4 },
    isPro: false,
    userRole: 'seguranca',
    password: '1a2b3c'
  },
  {
    id: 'patricia',
    name: 'Patrícia Nogueira',
    role: 'Gerente Financeira (Contadora)',
    badge: 'Financeiro',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    details: 'Contadora, 1.5 anos de empresa • Fim das 40 planilhas manuais',
    quote: 'Com o repasse PIX automatizado e emissão de NF para parceiros PRO, zeramos os erros de repasse.',
    metrics: { pendingPayouts: 'R$ 8.420,00', nfeIssuedToday: 14, conciliationError: '0%' },
    isPro: false,
    userRole: 'financeiro',
    password: '1a2b3c'
  },

  // GESTÃO & DIRETORIA EXECUTIVA
  {
    id: 'renata',
    name: 'Renata Bicalho',
    role: 'Head de Produto e Operações',
    badge: 'Head Ops',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    details: 'Ex-fintech, 2.5 anos de empresa • Automação de processos',
    quote: 'Reduzimos o vazamento de receita via PIX por fora e escalamos sem sobrecarregar o suporte.',
    metrics: { currentNPS: 74, targetNPS: 61, leakedRevenueBlocked: 'R$ 14.300/mês' },
    isPro: false,
    userRole: 'admin',
    password: '1a2b3c'
  },
  {
    id: 'marina',
    name: 'Marina Kessler',
    role: 'CTO e Cofundadora (Eng. Produção)',
    badge: 'CTO / Tech',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    details: 'Cofundadora, 5 anos de empresa • Arquitetura de microsserviços',
    quote: 'Eliminamos a dívida técnica do MVP antigo construindo uma plataforma robusta e escalável.',
    metrics: { uptime: '99.98%', apiLatencyMs: 180, testCoverage: '94%' },
    isPro: false,
    userRole: 'admin',
    password: '1a2b3c'
  },
  {
    id: 'thiago',
    name: 'Thiago Prado',
    role: 'CEO e Cofundador (Ex-Dev)',
    badge: 'CEO / Gestão',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    details: 'Cofundador, 5 anos de empresa • Expansão regional & Series A',
    quote: 'Vamos consolidar a TrocaJá como líder regional com processos 100% automatizados antes do Series A.',
    metrics: { gmvMonthly: 'R$ 184.000', proStoresCount: 1240, activeUsers: 58420 },
    isPro: false,
    userRole: 'admin',
    password: '1a2b3c'
  }
];

export const INITIAL_ITEMS = [
  {
    id: 'item-sup',
    title: 'Prancha de Stand Up Paddle',
    category: 'Esporte',
    categoryType: 'standard',
    pricePerDay: 80.00,
    depositAmount: 200.00,
    distanceKm: 2.5,
    cep: '14020-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Zona Sul',
    stateUf: 'SP',
    location: 'Zona Sul, Ribeirão Preto/SP',
    ownerId: 'thiago',
    ownerName: 'Thiago M.',
    ownerIsPro: false,
    commissionRate: 0.18,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80',
    description: 'Prancha inflável de alta performance para rios, represas e mar. Acompanha remo ajustável de alumínio, bomba de alta pressão e leal de segurança.',
    isBoosted: true,
    isSensitive: false,
    rating: 4.8,
    reviewsCount: 12,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19']
  },
  {
    id: 'item-drill',
    title: 'Furadeira de Impacto Profissional',
    category: 'Ferramentas',
    categoryType: 'standard',
    pricePerDay: 45.00,
    depositAmount: 350.00,
    distanceKm: 1.2,
    cep: '14010-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Centro',
    stateUf: 'SP',
    location: 'Centro, Ribeirão Preto/SP',
    ownerId: 'carlos',
    ownerName: 'Carlos Menezes',
    ownerIsPro: false,
    commissionRate: 0.18,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    description: 'Furadeira e parafusadeira de impacto 750W. Acompanha kit de brocas para concreto e madeira + maleta de transporte.',
    isBoosted: true,
    isSensitive: false,
    rating: 4.9,
    reviewsCount: 18,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18']
  },
  {
    id: 'item-projector',
    title: 'Projetor Epson Full HD 3000 Lumens',
    category: 'Eletrônicos',
    categoryType: 'standard',
    pricePerDay: 120.00,
    depositAmount: 500.00,
    distanceKm: 0.8,
    cep: '14015-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Vila Seixas',
    stateUf: 'SP',
    location: 'Vila Seixas, Ribeirão Preto/SP',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva',
    ownerIsPro: true,
    commissionRate: 0.09,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    description: 'Projetor cinema em casa e apresentações empresariais. Resolução Full HD 1080p, HDMI, Wi-Fi e auto-falante integrado.',
    isBoosted: false,
    isSensitive: false,
    rating: 5.0,
    reviewsCount: 22,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17']
  },
  {
    id: 'item-tent',
    title: 'Tenda para Festas 3x3m Impermeável',
    category: 'Festas',
    categoryType: 'standard',
    pricePerDay: 90.00,
    depositAmount: 300.00,
    distanceKm: 3.1,
    cep: '14080-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Campos Elíseos',
    stateUf: 'SP',
    location: 'Campos Elíseos, Ribeirão Preto/SP',
    ownerId: 'carlos',
    ownerName: 'Carlos Menezes',
    ownerIsPro: false,
    commissionRate: 0.18,
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80',
    description: 'Gazebo dobrável 3x3m montagem rápida em 2 minutos. Lona com proteção UV50+ e estrutura em alumínio reforçado.',
    isBoosted: false,
    isSensitive: false,
    rating: 4.7,
    reviewsCount: 14,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17']
  },
  {
    id: 'item-1',
    title: 'Serra Circular Profissional Bosch GKS 190 (1400W)',
    category: 'Ferramentas',
    categoryType: 'standard',
    pricePerDay: 45.00,
    depositAmount: 350.00,
    distanceKm: 1.8,
    cep: '14010-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Centro',
    stateUf: 'SP',
    location: 'Centro, Ribeirão Preto/SP (CEP: 14010-000)',
    ownerId: 'carlos',
    ownerName: 'Carlos Menezes',
    ownerIsPro: false,
    commissionRate: 0.18,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    description: 'Serra circular ideal para corte em madeira dura e compensados. Acompanha disco de metal duro e guia paralela.',
    isBoosted: true,
    isSensitive: false,
    rating: 4.9,
    reviewsCount: 12,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19', '2026-09-20']
  },
  {
    id: 'item-2',
    title: 'Drone Profissional DJI Mavic 3 Pro 4K + 3 Baterias',
    category: 'Drones & Filmagem',
    categoryType: 'sensitive',
    pricePerDay: 280.00,
    depositAmount: 1800.00,
    distanceKm: 3.2,
    cep: '14021-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Jardim Botânico',
    stateUf: 'SP',
    location: 'Jardim Botânico, Ribeirão Preto/SP (CEP: 14021-000)',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    ownerIsPro: true,
    commissionRate: 0.09,
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&auto=format&fit=crop&q=80',
    description: 'Drone para filmagem aérea em 4K/60fps com estabilização gimbal 3 eixos. *Requer envio de licença ANAC e comprovante de experiência.',
    isBoosted: true,
    isSensitive: true,
    sensitiveDocStatus: 'APROVADO',
    sensitiveDocUrl: 'https://anac.gov.br/registro_dji_mavic_3.pdf',
    rating: 5.0,
    reviewsCount: 8,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-18', '2026-09-19', '2026-09-20']
  },
  {
    id: 'item-3',
    title: 'Kit Som Ativo Yamaha DBR15 1000W + Mesa Behringer 12 Ch',
    category: 'Eventos & Áudio',
    categoryType: 'standard',
    pricePerDay: 190.00,
    depositAmount: 800.00,
    distanceKm: 2.1,
    cep: '14015-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Vila Seixas',
    stateUf: 'SP',
    location: 'Vila Seixas, Ribeirão Preto/SP (CEP: 14015-000)',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    ownerIsPro: true,
    commissionRate: 0.09,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    description: 'Sistema completo de som para festas até 200 pessoas. Inclui 2 caixas ativas de 1000W, pedestais e cabeamento completo.',
    isBoosted: false,
    isSensitive: false,
    rating: 4.8,
    reviewsCount: 29,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18']
  },
  {
    id: 'item-4',
    title: 'Betoneira 400 Litros Monofásica CSM Profissional',
    category: 'Ferramentas',
    categoryType: 'standard',
    pricePerDay: 85.00,
    depositAmount: 600.00,
    distanceKm: 4.5,
    cep: '14080-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Campos Elíseos',
    stateUf: 'SP',
    location: 'Campos Elíseos, Ribeirão Preto/SP',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    ownerIsPro: true,
    commissionRate: 0.09,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
    description: 'Betoneira reforçada para obras residenciais. Motor elétrico 2CV, pintura eletrostática e proteção de cremalheira.',
    isBoosted: false,
    isSensitive: false,
    rating: 4.7,
    reviewsCount: 15,
    availableCalendar: ['2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19']
  },
  {
    id: 'item-5',
    title: 'Réplica Treinamento Airsoft M4A1 Full Metal (Equipamento Tático)',
    category: 'Réplicas & Tático',
    categoryType: 'sensitive',
    pricePerDay: 120.00,
    depositAmount: 700.00,
    distanceKm: 5.8,
    cep: '14050-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Ipiranga',
    stateUf: 'SP',
    location: 'Ipiranga, Ribeirão Preto/SP',
    ownerId: 'carlos',
    ownerName: 'Carlos Menezes',
    ownerIsPro: false,
    commissionRate: 0.18,
    image: 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600&auto=format&fit=crop&q=80',
    description: 'Equipamento esportivo de airsoft para jogos e treinamentos táticos. *Ponta laranja obrigatória e exige nota fiscal registrada.',
    isBoosted: false,
    isSensitive: true,
    sensitiveDocStatus: 'EM_ANALISE',
    sensitiveDocUrl: 'https://trocaja.app/docs/airsoft_nf_carlos.pdf',
    rating: 4.6,
    reviewsCount: 3,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17']
  },
  {
    id: 'item-6',
    title: 'Gerador de Energia a Gasolina 3500W Toyama 220V',
    category: 'Eventos & Áudio',
    categoryType: 'standard',
    pricePerDay: 130.00,
    depositAmount: 900.00,
    distanceKm: 2.9,
    cep: '14090-000',
    city: 'Ribeirão Preto',
    neighborhood: 'Jardim Paulista',
    stateUf: 'SP',
    location: 'Jardim Paulista, Ribeirão Preto/SP',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    ownerIsPro: true,
    commissionRate: 0.09,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    description: 'Gerador com partida elétrica, autonomia de até 10h. Perfeito para festas ao ar livre e food trucks.',
    isBoosted: true,
    isSensitive: false,
    rating: 5.0,
    reviewsCount: 19,
    availableCalendar: ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19']
  }
];

export const INITIAL_BOOKINGS = [
  {
    id: 'res-801',
    itemId: 'item-1',
    itemTitle: 'Serra Circular Profissional Bosch GKS 190',
    itemImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    renterId: 'bianca',
    renterName: 'Bianca Ferreira',
    ownerId: 'carlos',
    ownerName: 'Carlos Menezes',
    startDate: '2026-09-10',
    endDate: '2026-09-12',
    dailyRate: 45.00,
    days: 2,
    subtotal: 90.00,
    insuranceFee: 15.00,
    commissionRate: 0.18,
    commissionAmount: 16.20,
    depositAmount: 350.00,
    totalPaid: 455.00,
    paymentMethod: 'PIX (In-App)',
    status: 'EM_DISPUTA',
    inspectionPickup: {
      timestamp: '2026-09-10T09:15:00Z',
      notes: 'Serra entregue em perfeito estado com lâmina nova e cabo sem avarias.',
      photos: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=80']
    },
    inspectionReturn: {
      timestamp: '2026-09-12T17:30:00Z',
      notes: 'Equipamento devolvido com dente da lâmina quebrado e cabo elétrico descascado por mau uso.',
      photos: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80']
    }
  },
  {
    id: 'res-802',
    itemId: 'item-3',
    itemTitle: 'Kit Som Ativo Yamaha DBR15 1000W',
    itemImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    renterId: 'diego',
    renterName: 'Diego Farias',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    startDate: '2026-09-15',
    endDate: '2026-09-17',
    dailyRate: 190.00,
    days: 2,
    subtotal: 380.00,
    insuranceFee: 25.00,
    commissionRate: 0.09,
    commissionAmount: 34.20,
    depositAmount: 800.00,
    totalPaid: 1205.00,
    paymentMethod: 'Cartão de Crédito',
    status: 'CONFIRMADA',
    inspectionPickup: null,
    inspectionReturn: null
  },
  {
    id: 'res-803',
    itemId: 'item-6',
    itemTitle: 'Gerador de Energia a Gasolina 3500W Toyama',
    itemImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&auto=format&fit=crop&q=80',
    renterId: 'diego',
    renterName: 'Diego Farias',
    ownerId: 'antenor',
    ownerName: 'Ferragens Silva (Antenor)',
    startDate: '2026-09-05',
    endDate: '2026-09-07',
    dailyRate: 130.00,
    days: 2,
    subtotal: 260.00,
    insuranceFee: 20.00,
    commissionRate: 0.09,
    commissionAmount: 23.40,
    depositAmount: 900.00,
    totalPaid: 1180.00,
    paymentMethod: 'PIX (In-App)',
    status: 'FINALIZADA',
    payoutStatus: 'CONCILIADO_PIX',
    nfeNumber: 'NFE-2026-8941',
    nfeUrl: 'https://trocaja.app/nfe/NFE-2026-8941.pdf'
  }
];

export const INITIAL_DISPUTES = [
  {
    id: 'disp-101',
    bookingId: 'res-801',
    itemTitle: 'Serra Circular Profissional Bosch GKS 190',
    category: 'Ferramentas',
    openedBy: 'carlos',
    openedByName: 'Carlos Menezes (Locador)',
    renterName: 'Bianca Ferreira',
    totalDeposit: 350.00,
    reportedDamageLevel: 'MODERADA',
    description: 'Locatária devolveu o equipamento com lâmina trincada e marcas profundas na carcaça.',
    suggestedRetentionPct: 35,
    suggestedRetentionAmount: 122.50,
    suggestedRefundAmount: 227.50,
    finalRetentionPct: null,
    finalRetentionAmount: null,
    status: 'EM_ANALISE',
    assignedAnalyst: 'lucas',
    assignedAnalystName: 'Lucas Andrade',
    auditLogs: [
      {
        timestamp: '2026-09-12T18:00:00Z',
        author: 'Sistema TrocaJá (Rules Engine)',
        action: 'Disputa Aberta - Sugestão Automática Gerada',
        details: 'Categoria: Ferramentas | Avaria: MODERADA (Lâmina + Cabo). Retenção recomendada: 35% (R$ 122,50).'
      }
    ]
  }
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    bookingId: 'res-803',
    reviewerName: 'Diego Farias',
    revieweeName: 'Ferragens Silva',
    rating: 5,
    comment: 'Gerador impecável, funcionou a festa toda sem falhar. Recomendo muito o Antenor!',
    createdAt: '2026-09-08T10:00:00Z',
    isThreatFlagged: false
  },
  {
    id: 'rev-2',
    bookingId: 'res-801',
    reviewerName: 'Bianca Ferreira',
    revieweeName: 'Carlos Menezes',
    rating: 1,
    comment: 'Se você não devolver minha caução inteira de R$ 350 vou deixar essa nota 1 estrela em todos os seus anúncios!',
    createdAt: '2026-09-12T19:30:00Z',
    isThreatFlagged: true,
    threatReason: 'Detecção de Ameaça/Chantagem: Nota 1 estrela condicionada à devolução de caução sob disputa.'
  }
];

export const INITIAL_MESSAGES = [
  {
    id: 'msg-1',
    senderId: 'bianca',
    senderName: 'Bianca Ferreira',
    text: 'Olá Carlos! Preciso da serra pra sábado. Dá pra fazer um desconto se eu pagar direto no seu PIX 1699887766 por fora do aplicativo?',
    timestamp: '2026-09-09T14:22:00Z',
    isBypassDetected: true,
    bypassReason: 'Tentativa de bypass detectada (PIX por fora / Número de telefone). Alerta de segurança emitido.'
  },
  {
    id: 'msg-2',
    senderId: 'carlos',
    senderName: 'Carlos Menezes',
    text: 'Oi Bianca! Prefiro fechar pela TrocaJá porque assim o sistema garante a caução e a vistoria de entrada e saída fica registrada!',
    timestamp: '2026-09-09T14:25:00Z',
    isBypassDetected: false
  }
];
